export const HERO_CONSTANTS = {
  PIN_SPACER_VH: 190,
  TRANSFORM_ORIGIN: '50% 46.25%',
  INITIAL_SCALE: 1,
  FINAL_SCALE: 9.5,
  TIMELINE_PHASES: {
    TEXT_EXIT_END: 0.76,
    TEXT_ACCELERATION_START: 0,
    TEXT_ACCELERATION_END: 0.92,
    ZOOM_START: 0.15,
    HARDWARE_DISSOLVE_START: 0.45,
    HARDWARE_DISSOLVE_END: 0.85,
    PORTAL_FULLCOVER: 0.92,
  },
} as const;
